FROM python:3.8.10
COPY requirements.txt .
COPY atomicloops_django-1.0-py3-none-any.whl .
RUN pip install atomicloops_django-1.0-py3-none-any.whl
RUN pip install -r requirements.txt
RUN pip install "drf-yasg[validation]"
RUN pip install git+https://github.com/atomic-loops/atomicloops-django-logger
WORKDIR /opt
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]